DROP TABLE IF EXISTS earthquakes;
CREATE TABLE earthquakes (
  quake_time TIMESTAMP WITH TIME ZONE,
  latitude FLOAT,
  longitude FLOAT,
  quakedepth FLOAT,
  magnitude FLOAT,
  magnitude_type VARCHAR(3),
  nst INTEGER,
  gap INTEGER,
  dmin FLOAT,
  rms FLOAT,
  net VARCHAR(3),
  id VARCHAR(12),
  updated TIMESTAMP WITH TIME ZONE,
  place TEXT,
  event_type VARCHAR(10),
  horizontal_error FLOAT,
  depth_error FLOAT,
  magnitude_error FLOAT,
  magnitude_nst INTEGER,
  review_status VARCHAR(9),
  location_source VARCHAR(3),
  magnitude_source VARCHAR(3)
);